import { StyleSheet, Platform } from 'react-native';

// Function to create dynamic styles with theme colors and screen size
export const createStyles = (isLargeScreen: boolean, colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    content: {
      flex: 1,
      padding: 16,
    },
    welcomeSection: {
      marginBottom: 20,
    },
    welcomeTitleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      marginBottom: 16,
    },
    welcomeTitleContainer: {
      flex: 1,
    },
    welcomeTitle: {
      fontSize: 24,
      fontWeight: "600",
      color: colors.text,
      marginBottom: 8,
    },
    welcomeText: {
      fontSize: 16,
      color: colors.secondary,
      lineHeight: 22,
    },
    searchButton: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: colors.card,
    },
    header: {
      padding: 16,
      paddingBottom: 20,
    },
    title: {
      fontSize: 24,
      fontWeight: "800",
      color: colors.text,
      marginBottom: 10,
      letterSpacing: -0.5,
    },
    gridContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
      marginBottom: 20,
      marginTop: 4,
      justifyContent: "space-between",
    },
    emojiCard: {
      width: isLargeScreen ? "23%" : "48%",
      height: 140,
      padding: 16,
      marginBottom: 0,
      borderRadius: 16,
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
      transform: [{ scale: 1 }],
      borderWidth: 1,
      borderColor: Platform.OS === 'ios' ? 'rgba(0,0,0,0.05)' : 'transparent',
      overflow: "hidden",
    },
    selectedCard: {
      transform: [{ scale: 1.03 }],
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 5,
      },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
      borderWidth: 2,
      borderColor: "rgba(255,255,255,0.3)",
    },
    unselectedCard: {
      opacity: 0.7,
      transform: [{ scale: 0.98 }],
      shadowOpacity: 0.1,
    },
    emojiWrapper: {
      width: 48,
      height: 48,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 12,
      borderRadius: 24,
      // Removed grey background to match modern design
    },
    emojiText: {
      fontSize: 32,
    },
    emojiInfoContainer: {
      alignItems: "center",
    },
    emojiLabel: {
      fontSize: 16,
      color: "white",
      fontWeight: "bold",
      letterSpacing: 0.3,
      textAlign: "center",
      marginBottom: 6,
      textShadowColor: 'rgba(0, 0, 0, 0.3)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    emojiCount: {
      fontSize: 12,
      color: "rgba(255, 255, 255, 0.9)",
      textAlign: "center",
      fontWeight: '500',
      textShadowColor: 'rgba(0, 0, 0, 0.3)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    // New styles for expandable content matching Reading Plans
    emojiDetailContainer: {
      marginVertical: 16,
      borderRadius: 16,
      shadowColor: colors.text,
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 4,
      borderWidth: 1,
      borderColor: Platform.OS === "ios" ? "rgba(0,0,0,0.05)" : "transparent",
      overflow: "hidden",
    },
    emojiDetailHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 0,
      paddingHorizontal: 20,
      paddingVertical: 16,
      backgroundColor: colors.card,
    },
    emojiDetailIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 12,
    },
    emojiDetailTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: colors.text,
      letterSpacing: -0.3,
      flex: 1,
    },
    emojiDetailCount: {
      fontSize: 16,
      color: colors.secondary,
      marginBottom: 16,
      fontWeight: "500",
    },

    emojiDetailContent: {
      paddingHorizontal: 20,
      paddingBottom: 20,
      backgroundColor: colors.card,
    },
    emojiDetailIntro: {
      color: colors.text,
      fontSize: 16,
      lineHeight: 24,
      marginBottom: 20,
      textAlign: 'center',
    },
    expandButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 16,
      paddingHorizontal: 20,
      borderTopWidth: 1,
      backgroundColor: colors.card,
    },
    expandButtonText: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text,
    },
    expandIcon: {
      color: colors.secondary,
    },
    stepsContainer: {
      marginTop: 16,
    },
    stepRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginBottom: 16,
    },
    stepNumber: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 12,
      marginTop: 2,
    },
    stepNumberText: {
      color: "white",
      fontWeight: "700",
      fontSize: 14,
    },
    stepContent: {
      flex: 1,
    },
    stepTitle: {
      color: colors.text,
      fontWeight: "700",
      fontSize: 16,
      marginBottom: 6,
    },
    stepDescription: {
      color: colors.secondary,
      fontSize: 15,
      lineHeight: 22,
    },
    conclusionContainer: {
      marginTop: 20,
      backgroundColor: colors.background,
      borderRadius: 12,
      padding: 16,
    },
    conclusionTitle: {
      color: colors.text,
      fontWeight: "700",
      fontSize: 16,
      marginBottom: 8,
    },
    conclusionText: {
      color: colors.secondary,
      fontSize: 15,
      lineHeight: 22,
    },
    backButton: {
      position: "absolute",
      top: 16,
      right: 16,
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: "rgba(0,0,0,0.2)",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 10,
    },
    // Add back missing styles that are still used
    reactionsContainer: {
      paddingHorizontal: 4,
    },
    reactionItemContainer: {
      marginBottom: 8,
    },
    speechBubbleContainer: {
      position: "relative",
      zIndex: 1,
      marginBottom: 2,
    },
    reactionEmoji: {
      fontSize: 30,
      padding: 5,
      elevation: 3,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
    },
    indicatorContainer: {
      position: "absolute",
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      zIndex: 100,
    },
    noteIconContainer: {
      padding: 0,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 1,
    },
    referenceText: {
      fontSize: 12,
      color: colors.secondary,
      textAlign: "right",
      marginTop: 1,
      paddingRight: 16,
      paddingBottom: 2,
      fontWeight: "500",
    },
    contentContainer: {
      paddingBottom: 16,
    },
    emptyStateContainer: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 48,
      paddingHorizontal: 32,
      marginTop: 20,
      opacity: 0.7,
    },
    emptyStateText: {
      fontSize: 16,
      color: colors.secondary,
      textAlign: "center",
      marginTop: 16,
    },
    longPressHint: {
      fontSize: 12,
      color: colors.secondary,
      textAlign: "center",
      marginTop: 8,
      marginBottom: 4,
      paddingHorizontal: 16,
      fontStyle: "italic",
      opacity: 0.7,
    },

    // Jump to passage modal styles
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContainer: {
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 20,
      marginHorizontal: 20,
      maxWidth: 400,
      width: '88%',
      alignSelf: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 10,
      },
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 10,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.text,
      textAlign: 'center',
      marginBottom: 8,
    },
    modalSubtitle: {
      fontSize: 15,
      color: colors.secondary,
      textAlign: 'center',
      marginBottom: 20,
      lineHeight: 20,
    },
    modalButtonContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      justifyContent: 'center',
    },
    modalButton: {
      flex: 1,
      minWidth: 90,
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 6,
    },
    modalButtonPrimary: {
      backgroundColor: '#007AFF',
    },
    modalButtonSecondary: {
      backgroundColor: colors.border,
    },
    modalButtonDanger: {
      backgroundColor: '#FF3B30',
    },
    modalButtonText: {
      fontSize: 15,
      fontWeight: '600',
      color: 'white',
    },
    modalButtonTextSecondary: {
      color: colors.text,
    },
    // Filter interface styles
    filterHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
      marginTop: 4,
      paddingHorizontal: 4,
    },
    filterHeaderLeft: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    filterHeaderText: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.text,
      letterSpacing: -0.3,
      marginRight: 8,
    },
    activeFilterBadge: {
      backgroundColor: '#007AFF',
      borderRadius: 10,
      paddingHorizontal: 8,
      paddingVertical: 2,
      minWidth: 20,
      alignItems: 'center',
    },
    activeFilterText: {
      color: 'white',
      fontSize: 12,
      fontWeight: '600',
    },
    filterButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
    },
    filterButtonActive: {
      backgroundColor: '#E3F2FD',
      borderColor: '#007AFF',
    },
    filterButtonText: {
      fontSize: 14,
      fontWeight: '500',
      color: colors.text,
      marginLeft: 4,
    },
    filterButtonTextActive: {
      color: '#007AFF',
    },
    // Filter panel styles
    filterPanel: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.5)',
      zIndex: 1000,
    },
    filterPanelContent: {
      backgroundColor: colors.background,
      flex: 1,
      paddingTop: 60, // Account for status bar
      paddingHorizontal: 20,
      paddingBottom: 40,
    },
    filterPanelHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    filterPanelTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.text,
    },
    filterPanelHeaderButtons: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    closeFilterButton: {
      marginLeft: 10,
    },
    clearAllButton: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 6,
      backgroundColor: colors.card,
    },
    clearAllText: {
      fontSize: 14,
      color: colors.text,
      fontWeight: '500',
    },
    filterSection: {
      marginBottom: 24,
    },
    filterSectionTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 12,
    },
    filterOption: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
      paddingHorizontal: 4,
    },
    filterCheckbox: {
      width: 20,
      height: 20,
      borderRadius: 4,
      borderWidth: 2,
      borderColor: colors.border,
      marginRight: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filterCheckboxActive: {
      backgroundColor: '#007AFF',
      borderColor: '#007AFF',
    },
    filterOptionText: {
      fontSize: 16,
      color: colors.text,
      flex: 1,
    },
    sourceColorOption: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    sourceColorDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
      marginRight: 8,
    },
    applyButton: {
      backgroundColor: '#007AFF',
      paddingVertical: 16,
      paddingHorizontal: 24,
      borderRadius: 12,
      alignItems: 'center',
      marginTop: 20,
      marginBottom: 20,
    },
    applyButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '600',
    },
    clearFiltersButton: {
      padding: 4,
    },
  });
